debug = false

[target]
path = "V:\\Games\\Standalone\\Star Rail\\Games\\StarRail.exe"
args = []
delay = 0

[launcher]
path = "V:\\Program Files\\Star Rail\\launcher.exe"
args = []
delay = 0
kill_after_launch = false
kill_after_target_exit = true